name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: curl, dom, json, libxml, mbstring, simplexml

      - name: Validate Composer manifest
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run lint, static analysis, and smoke tests
        env:
          SFM_APP_NAME: SimpleFeedMaker
          SFM_TRUSTED_PROXIES: 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22
          SFM_TEST_FIXTURE_DIR: ${{ github.workspace }}/tests/fixtures
          SFM_TEST_ALLOW_LOCAL_URLS: '1'
        run: composer ci
